service:
  name: samples-apigateway-websocket-chat

provider:
  name: aws
  stage: ${ opt:stage, 'dev' }
  region: ${ opt:region, 'ap-northeast-1' }
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [ ChatConnectionsTable, Arn ]
  environment:
    TABLE_NAME:
      Ref: ChatConnectionsTable
  websocketsApiName: ${self:service.name}-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.message

functions:
  connect:
    handler: connect/app.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: disconnect/app.handler
    events:
      - websocket:
          route: $disconnect
  sendmessage:
    handler: sendmessage/app.handler
    events:
      - websocket:
          route: sendmessage

resources:
  Resources:
    ChatConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service.name}-connections-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        SSESpecification:
          SSEEnabled: True