service:
  name: samples-apigateway-websocket-chat

provider:
  name: aws
  stage: ${ opt:stage, 'dev' }
  region: ${ opt:region, 'ap-northeast-1' }
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [ ChatConnectionsTable, Arn ]
  environment:
    TABLE_NAME:
      Ref: ChatConnectionsTable
  websocketApiName: ${self:service.name}-${self:provider.stage}
  websocketApiRouteSelectionExpression: $request.body.action

functions:
  connect:
    handler: handler.connect
    events:
      - websocket:
          routeKey: $connect
  disconnect:
    handler: handler.disconnect
    events:
      - websocket:
          routeKey: $disconnect
  defaultMessage:
    handler: handler.defaultMessage
    events:
      - websocket:
          routeKey: $default
  sendMessage:
    handler: handler.sendMessage
    events:
      - websocket:
          routeKey: sendMessage

resources:
  Resources:
    ChatConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service.name}-connections-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: ConnectionId
            AttributeType: S
        KeySchema:
          - AttributeName: ConnectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        SSESpecification:
          SSEEnabled: True